import express, { Router } from "express";
import Verify from "../../Authenticate/verify";
import { getAllTickets, getTicket, createTicket } from "./Controller";
export let TicketRouter = Router();
TicketRouter.get("/", getAllTickets);
TicketRouter.get("/:index", Verify.user, getAllTickets);
TicketRouter.get("/:tid", Verify.user, getTicket);
TicketRouter.post("/", createTicket);
TicketRouter.put("/:tid", Verify.user, getTicket);
TicketRouter.delete("/:tid", Verify.user);
